name: Laravel

on:
  push:
    branches: [ "hotfix" ]
  pull_request:
    branches: [ "hotfix" ]

jobs:
  laravel-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install PHP latest
              run: |
                  sudo apt remove php -y
                  sudo apt update
                  sudo add-apt-repository ppa:ondrej/php
                  sudo apt update
                  sudo apt -y install php
                  sudo apt update
                  sudo apt install php-curl php-xml php-mbstring php-mysql -y

            - name: Start Mariadb
              run: |
                  sudo systemctl start mysql.service
                  mysql -uroot -p -e 'CREATE DATABASE IF NOT EXISTS primerproyectotest;'

            - name: Install Composer dependencies
              run: composer update

            - name: Run unit tests
              run: |
                  php artisan migrate
                  php artisan test
